name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: '25.1.8937393'
        cmake-version: '3.22.1'

    - name: Accept Android Licenses
      run: |
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

    - name: Clean build environment
      run: |
        rm -rf ~/.gradle/caches
        rm -rf ~/.android/build-cache
        rm -rf build
        rm -rf .gradle

    - name: Configure Maven Mirrors
      run: |
        mkdir -p ~/.gradle
        cat << EOF > ~/.gradle/init.gradle
        allprojects {
            repositories {
                maven { url 'https://maven.aliyun.com/repository/public' }
                maven { url 'https://maven.aliyun.com/repository/google' }
                maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
                google()
                mavenCentral()
            }
        }
        EOF
        echo "systemProp.http.proxyHost=mirrors.aliyun.com" >> ~/.gradle/gradle.properties
        echo "systemProp.https.proxyHost=mirrors.aliyun.com" >> ~/.gradle/gradle.properties

    - name: Build APK
      env:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m"
      run: |
        chmod +x gradlew
        ./gradlew clean
        ./gradlew assembleRelease --stacktrace --no-daemon

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk