name: Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build APK
      run: ./gradlew assembleDebug
      
    - name: Find APK
      id: find-apk
      run: |
        APK_PATH=$(find app/build/outputs/apk/ -name "*.apk" | head -1)
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "Found APK: $APK_PATH"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: ${{ steps.find-apk.outputs.apk_path }}
